POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Hello world",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "CSS is hard",
    "important": true
}