POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Hello world",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "CSS is hard",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmFoIiwiaWQiOiI2NGYzNDk3MzA3N2RiYWZjYTY0OWQ1NWYiLCJpYXQiOjE2OTM4MzI1MTl9.D2wKSArlDUm_bEPcPkUX9CFXQrNOVXOoxLE-uVTEZO0

{
    "content": "annyeong is hello 22",
    "important": true
}